#version 450
layout(local_size_x = 8, local_size_y = 8) in;

layout(set = 0, binding = 0, r16f) uniform readonly image2D uSrc;
layout(set = 0, binding = 1, r16f) uniform writeonly image2D uDst;

layout(push_constant) uniform Push {
    uvec2 dst_size;
} push;

void main() {
    ivec2 dst = ivec2(gl_GlobalInvocationID.xy);
    if (dst.x >= int(push.dst_size.x) || dst.y >= int(push.dst_size.y))
        return;

    ivec2 src_base = dst * 2;
    ivec2 src_size = imageSize(uSrc);
    float a = imageLoad(uSrc, clamp(src_base + ivec2(0, 0), ivec2(0), src_size - 1)).r;
    float b = imageLoad(uSrc, clamp(src_base + ivec2(1, 0), ivec2(0), src_size - 1)).r;
    float c = imageLoad(uSrc, clamp(src_base + ivec2(0, 1), ivec2(0), src_size - 1)).r;
    float d = imageLoad(uSrc, clamp(src_base + ivec2(1, 1), ivec2(0), src_size - 1)).r;
    imageStore(uDst, dst, vec4(0.25 * (a + b + c + d), 0.0, 0.0, 0.0));
}
